---
project: lid_segmentation
task: cam_generation

devices:
  - 'cuda:1'
  - 'cuda:2'

data:
  path: /datasets/extra_space2/LID/ILSVRC/Data/DET/train/irn_list_nohuman_confident_0.8.json
  output_path: /datasets/extra_space2/LID/ILSVRC/Data/DET/train/outputs/nohuman/cam
  transform:
    size: 352
    augmentation_scope: none
    images_normalization: default
    images_output_format_type: float
    size_transform: resize

model:
  arch: vgg_gap
  pretrained: True
  weights_path: /home/ostap/logs/vgg_nohuman.h5
  target_layer: extra_convs.4
  classes: 200

extraction_method: grad-cam
scales: [1.0, 0.5, 0.75, 2.0]
prediction_threshold: 0.5
