---
project: lid_segmentation
task: cam_generation
log_path: ~/logs

devices:
  - 'cuda:1'
  - 'cuda:2'

train:
  path: ILSVRC/Data/DET/train/train2014_onlyhuman.json
  transform:
    size: &SIZE 352
    augmentation_scope: strong
    images_normalization: &IMAGES_NORMALIZATION default
    images_output_format_type: &IMAGES_OUTPUT_FORMAT_TYPE float
    size_transform: resize

val:
  path: ILSVRC/Data/DET/train/val2014_onlyhuman.json
  transform:
    size: *SIZE
    augmentation_scope: none
    images_normalization: *IMAGES_NORMALIZATION
    images_output_format_type: *IMAGES_OUTPUT_FORMAT_TYPE
    size_transform: resize

model:
  arch: vgg_gap
  pretrained: True
  classes: 2
  loss:
    name: binary_cross_entropy
  metrics:
    - hamming
    - mlaccuracy
    - mlf1

num_epochs: 50
batch_size: 40
optimizer:
  name: Adam
  parameters:
    lr:
      - 0.0001
      - 0.0002
      - 0.001
      - 0.002
    weight_decay: 1.0e-05

scheduler:
  name: step
  step_size: 3
  gamma: 0.2

monitor:
  method: epochs
  interval: 10


